set nocompatible
set smartindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set cursorline
set lines=50
set columns=100
set go=
set backspace=2
set mouse=a
set nu
set clipboard=unnamedplus
set ignorecase
set smartcase
map ; :
noremap H h
noremap J gj
noremap K gk
noremap L l
