echo "(info) 'expression1.in' is generated by hand."

echo "(info) Generating 'expression2.in'..."
./datagen.py --only-or --no-not --no-brackets -t5 > expression2.in

echo "(info) Generating 'expression3.in'..."
./datagen.py --no-not --no-brackets > expression3.in

echo "(info) Generating 'expression4.in'..."
./datagen.py --no-brackets > expression4.in

echo "(info) Generating 'expression5.in'..."
./datagen.py --no-brackets -not1 > expression5.in

echo "(info) Generating 'expression6.in'..."
./datagen.py -n100 > expression6.in

echo "(info) Generating 'expression7.in'..."
./datagen.py -n100 -not1 > expression7.in

echo "(info) Generating 'expression8.in'..."
./datagen.py > expression8.in

echo "(info) Generating 'expression9.in'..."
./datagen.py -not1 > expression9.in

echo "(info) Generating 'expression10.in'..."
./datagen.py -not1 -t5 > expression10.in

echo "(info) Compiling standard program..."
g++ expression.cpp -O3 -std=c++11 -DNO_FILE_IO -Wno-unused-result -o std

echo "(info) Generating 'expression1.out'..."
./std < expression1.in > expression1.out

echo "(info) Generating 'expression2.out'..."
./std < expression2.in > expression2.out

echo "(info) Generating 'expression3.out'..."
./std < expression3.in > expression3.out

echo "(info) Generating 'expression4.out'..."
./std < expression4.in > expression4.out

echo "(info) Generating 'expression5.out'..."
./std < expression5.in > expression5.out

echo "(info) Generating 'expression6.out'..."
./std < expression6.in > expression6.out

echo "(info) Generating 'expression7.out'..."
./std < expression7.in > expression7.out

echo "(info) Generating 'expression8.out'..."
./std < expression8.in > expression8.out

echo "(info) Generating 'expression9.out'..."
./std < expression9.in > expression9.out

echo "(info) Generating 'expression10.out'..."
./std < expression10.in > expression10.out

