echo "(info) 'expression1.in' is generated by hand."

echo "(info) Generating 'expression2.in'..."
./datagen.py --only-or --no-not --no-brackets > expression2.in

echo "(info) Generating 'expression3.in'..."
./datagen.py --no-not --no-brackets > expression3.in

echo "(info) Generating 'expression4.in'..."
./datagen.py --no-brackets > expression4.in

echo "(info) Generating 'expression5.in'..."
./datagen.py --no-brackets > expression5.in

echo "(info) Generating 'expression6.in'..."
./datagen.py -n100 > expression6.in

echo "(info) Generating 'expression7.in'..."
./datagen.py -n100 > expression7.in

echo "(info) Generating 'expression8.in'..."
./datagen.py > expression8.in

echo "(info) Generating 'expression9.in'..."
./datagen.py > expression9.in

echo "(info) Generating 'expression10.in'..."
./datagen.py > expression10.in
